// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yrbssqlvlmyfqeywlwyt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlyYnNzcWx2bG15ZnFleXdsd3l0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkzNDUwMzcsImV4cCI6MjA3NDkyMTAzN30.L-_rVq3z3t0unej_J2VDUcdsUfKYd-c0bw3AjNj62ns";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});